### PR TITLE
When no version is specified, return healthy if any version is available

### PR DESCRIPTION
**Pull request by codycollier**
This PR completes the following, raised by @adriangay in Issue #1:
- [x] Add logic to check for any/first version which has AVAILABLE state, if no version is specified
- [x] Add new test and adjust assertions to account for improved behavior

### CODE REVIEW

**Comment by codycollier** [comment]
Updated github action configs in main (goreleaser was out of date and breaking).  Rebased and pushed.

**Review by aidandunlop — APPROVED** [review]

**Review by alexgeorgousis — APPROVED** [review]
This is great, thank you for fixing this 👏

**Review by adriangay — APPROVED** [review]
😄

**Comment by codycollier** [comment]
Thanks all!

**Pull request merged**
